# -*- coding: utf-8 -*-
"""AOC.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cOvcJT5J8Bohn2GlyRiYvlGUUysCIPUq
"""

radius=float(input("enter radius of circle: "))
area= radius**2*3.14
print (area)