# -*- coding: utf-8 -*-
"""positive.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wckIBbEGJzjNhk0PiBGQoDn6sGp9IZK9
"""

list1=[1,-2,3,-4,5]
for x in list1:
  if x>0:
    print (x)